import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

// ─────────────────────────────────────────────────────────────
//  BusTelemetry — Mongoose Schema
//
//  Indexing Strategy
//  ─────────────────
//  1. `2dsphere` on `location` — enables efficient geospatial
//     queries (e.g., "all buses within 500m of a stop") using
//     MongoDB's GeoJSON engine.  Required for $geoNear / $near
//     aggregation stages used by the "Arriving Soon" push alert.
//
//  2. Compound index on `(routeId, timestamp)` — the dominant
//     query pattern for a parent's dashboard is:
//       "give me the last N coordinates for route X".
//     Covering both fields lets Mongo use the index exclusively
//     without loading documents off disk (index scan only).
//
//  3. TTL index on `timestamp` (expireAfterSeconds: 2_592_000)
//     — Mongo's background TTL task auto-deletes documents older
//     than 30 days.  This keeps the collection from growing
//     unbounded even with 1-second GPS updates across 50 buses
//     (~4.3 GB / year per bus avoided by default retention).
//
//  4. `busId` single-field index — for admin fleet heatmap
//     queries filtered by a specific vehicle.
//
//  Collection type: Standard (not native time-series) to retain
//  secondary index flexibility.  Upgrade path to native
//  time-series available once MongoDB 7 is confirmed in prod.
// ─────────────────────────────────────────────────────────────

/**
 * GeoJSON Point sub-document.
 * Mongoose requires the exact { type, coordinates } shape for
 * 2dsphere indexing to function correctly.
 */
export class GeoJsonPoint {
  @Prop({ type: String, enum: ['Point'], default: 'Point', required: true })
  type: 'Point';

  /**
   * [longitude, latitude] — NOTE: GeoJSON is lng/lat order,
   * not the conventional lat/lng.  Client SDKs must match this.
   */
  @Prop({ type: [Number], required: true })
  coordinates: [number, number];
}

export type BusTelemetryDocument = BusTelemetry & Document;

@Schema({
  collection: 'bus_telemetry',
  // Disable Mongoose version key (__v) — not needed for append-only telemetry
  versionKey: false,
  // Enable automatic `createdAt` / `updatedAt` (we alias createdAt → timestamp below)
  timestamps: false,
})
export class BusTelemetry {
  /**
   * References `BusRoute.id` from PostgreSQL.
   * Stored as a plain string (UUID) so the telemetry collection
   * remains independent of Postgres schema changes.
   */
  @Prop({ type: String, required: true, index: true })
  busId: string; // Vehicle / bus asset ID (from BusRoute PG UUID)

  @Prop({ type: String, required: true })
  routeId: string; // BusRoute.id (PG UUID)

  @Prop({ type: String, required: true })
  driverId: string; // User.id (PG UUID) of the driver

  @Prop({ type: String })
  matronId?: string; // User.id of the matron on this trip (if present)

  /**
   * GeoJSON Point — indexed with 2dsphere for spatial queries.
   * Index declared via SchemaFactory + schema.index() below.
   */
  @Prop({ type: GeoJsonPoint, required: true })
  location: GeoJsonPoint;

  /** Speed in km/h reported by the device GPS */
  @Prop({ type: Number, min: 0, max: 200 })
  speed?: number;

  /** Compass heading in degrees (0–359) */
  @Prop({ type: Number, min: 0, max: 359 })
  heading?: number;

  /**
   * Number of students currently on board.
   * Updated by the NFC boarding events.
   */
  @Prop({ type: Number, default: 0 })
  occupancy?: number;

  /**
   * Battery level of the driver's device (0–100%).
   * Used to proactively alert if device is about to die mid-route.
   */
  @Prop({ type: Number, min: 0, max: 100 })
  batteryLevel?: number;

  /**
   * ISO timestamp of the GPS reading FROM the device.
   * Stored as Date for TTL index and time-range queries.
   * This is the authoritative time field — NOT createdAt.
   */
  @Prop({ type: Date, required: true, default: () => new Date() })
  timestamp: Date;

  /**
   * Trip session identifier — groups all telemetry points
   * belonging to a single bus run (morning or afternoon trip).
   * Generated by the driver app at trip start.
   */
  @Prop({ type: String })
  tripSessionId?: string;
}

export const BusTelemetrySchema = SchemaFactory.createForClass(BusTelemetry);

// ── Indexes ──────────────────────────────────────────────────

// 1. 2dsphere — enables $near, $geoNear, $geoWithin queries
BusTelemetrySchema.index({ location: '2dsphere' });

// 2. Compound covering index for the primary dashboard query pattern
//    { routeId + timestamp DESC } — index scan without doc fetch
BusTelemetrySchema.index({ routeId: 1, timestamp: -1 });

// 3. TTL — Mongo auto-deletes docs where timestamp < now - 30 days
BusTelemetrySchema.index(
  { timestamp: 1 },
  { expireAfterSeconds: 30 * 24 * 60 * 60 }, // 2_592_000 seconds
);

// 4. busId single-field for fleet heatmap / admin queries
BusTelemetrySchema.index({ busId: 1, timestamp: -1 });

// 5. tripSessionId — reconstruct full route playback
BusTelemetrySchema.index({ tripSessionId: 1, timestamp: 1 });
